version: 0.2
env:
  variables:
    S3BUCKET: meh-sam
    
phases:
  install:
    commands:
      - pip install --upgrade --user awscli
      
  build:
    commands:
      - aws s3 sync ./ s3://meh-sam/github2s3-buildcommand/
      
artifacts:
  files:
    - "**/*"
  
